[workspace]

members = [
    "bot",
    "libtetris",
    "battle",
    "cc-client",
    "opening-book",
    "c-api",
    "compare",
    "optimizer",
    "opening-book/book-builder",
    "opening-book/pc-gen",
    "tbp",
    "test"
]

[profile.release]
lto = true
